apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgBSXv8M6IQkBr6wizA7Ta3ktMkd4xUXpTFQrEYHIZ2hBuQ4zqikFFoUUiWAtoHcALPEAhZ+NG1BDlwXkBGp9EfXsxEieCazcFJwnkZeYPvs2TYfzb2SuvyzQmD+eYwdU/NavGpOahCXo1gswyO9Y03fDKkAEa37NYqdaZzsjF4Ld3kp7Mvjt8x3qh/Z028vUSYYRz60dN3vt1EUjANSQapKZo8ei0fqc2xtUKaQ5UcHSqxecHRNOkaiW0Ei9v+qvC5S2anncD3wDUbx1PgaWP5NtitsoeZ/L9/2UBiGCRNRzyCb0fAH+ByuZeWVXvS88wKt+2qP97RRrvyhH7171KR6eRiMs/YU9ATulphznSxUCDiSeiH30V8djHhQcNkEOqBaevS7oP1NSDJLaWhI7Qb8LXH9gf6sgNpSZckZglCjiTiCPTrAi6bChfuxFVBzleDawVOrZ7cTU6QXcnkeTJcp4rkXsSeuqUe9OdWtOnDuxOiLokDpa9U2DagR9qF9lQ6w7MOJjFLhXzz8+vTf5v7wrgWpg/mGy1d5QaQmLYT26FIMTASL9KffGkPe3tsjRIFWyLOA1SvbbDCi3+QfmzP1O6G5U/p79kG9YFb3LPvR61BnHAlvyhBJJZ1l0FWQyjeLMJ06lfR0bnKWqQPZ7htXQGz5gDwYdVs/d0+pGwXXlkJY+8AhxTuMPyZ4/MPk361CVwFcYd54j4c5p5zMyTyCQqJVpQuaRgSpLUEYjZ2zyAJbXBnFY5eFINRy5wvlud64ZV0pX2gc72Hi+3GwrTiqcFbkz11BSEUQv+0+dAwh2cuMlxCwE1crkPOW7Cflmjd69bcmRRFjVRfq+G2VKJ8Ch60ZO+Xlj/UpSnJtRTUPGkmMvreteunp3duB5ZaUivlMwTSET+BrKROWm+C59IXxTXshiDl3UZAekTfD0jVOUA9a4FcXaJUsRoVVieV0+QaaxNEbb9xNrhw2eLhaIBO90qDYZkbkMspWrhMjQltm7pwxr0tweURppMq8PUFpcJRibtwGCdyhq4l0X3hCRTT4i5lreA8YWgYQEsnUxf6Ot+0oKi8l8XNLe6ELhweJkBGjgk53rEsr93ME4qpdm42kN2HlnxeArXsSWx8IBNTybGLgA7nmCFKB7SnasmetIUbeZXirIdV5msqFcrm+cXidqWZUlo+++tslOPR7cbbWsC5LYFEzgEvwCed20EBOowPiRDrHMUAb0vxrXCkmKey/t216VD6fqcHZSgXNiynEWnObmkfWkks6MbNe/ZXLY3hr7i/AQc0RxFlSh7UZQHx3zvBv/GzMwEegHJyK1ciBu5Biz+yLe7KGmVkKn6OoaVSR
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

