apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: openshift-marketplace
spec:
  encryptedData:
    .dockerconfigjson: AgCONl9GUk9FgRRVlLIDB1X56DJnUPFbp/eT7a2WtduRC1VmYXrPKmZPU9CN8qzjAIkvt1StzxjoQ/EKZttnGwHF4laZY/RpyqJPDe2+3URDwPdCJAbYqkV7LRA0iJstnqhLs/MAUEpcaHbpXOWkmV31SR6dEa4vs6mZOVgsPESeH93rhxXrZjjv8ya3okMG5FXV1q0vv9vtaRaiUFyWGsKLOBDAOPWQ0uLxIDqDReN3igQP1NNKcWOIJz5V1uzqex4QcaO6XwT7tBRGxhjhMygxQhkrUfK7ECwGB9e0C99KSpdxdDt7NaVOiAX5TOdaZHGKEGe0Y/f7mWJCKYzPl9vGdaJUus7uvCHjlQ2OmbJfz4hiJSJWXbQYoMOfrgn2IZ0TTVo21DPqEMGhG1gDk4fmNVp94lv9tIsANIxub7mrDxeASdgq/CM9khXLrvNCTJvRR3HxxbUrZyIPK18CFJZHL/Qdy4jkfW7VfDYiuFL7m/70ANLnzc4DDy/83HTpa9COQMIfwLt5pwp4twYxTALjSXs5XekJlSN6UiurE9r+EkZPuCAQB6nNKu551hc6auIRKP/8I2c+G6KhOmDi+oL3Yz3Ffzx9oOQND6ZRbT3HgamcGqhAgeoxHARXV0CduilTidMXmCGTWkLYap3bSfSK16CsF+kbSATge1jhzRYy5FYw62Z72FrLZ23mdBWtRWMutk+KgaDb8q8znxHv6q7tGuC8KolwNLCjLkq0h+VXg8VqiZycFC/517Q8IK/ckn/2SRjzHWTFTBi/HUn3ir7fS2n37twc4j6g4MWN7e1zKZny93x2j2vusKto55w45iNMpcCjgFNNE8gTgqXzwcNLuVFVAp1TfMNwnNEkWU4Jl7uLg1fT417HqLR07bJ6d1svCpdm0cdDEeLC62RexSduT1WGRh1xh5cbNnbq616UbOUBwo/j0byIJtRtNQeqKhFZWuHVlLxsAa2h+AIOjIxOXb5/xycc0N/PZkteci7o3duFxKgTKtwg6FrKhvfZQNQen7VouUe9KhTKGmX6NPRjv8tkJmCH9oDk4DuDq9PpBbNN7vX9OIUxxfJoFJtnoboZr5jlOWmae9NYqBJTf8pMFgVzowC95Vy/tuRSsCx5cWO6Z7C39uNiy1AmUBavlvxAx+NE10l21ye09fIPIWqieFeXIdTDJjoS8AkjlC4RAAenG0zu2cnvkb42BP80UVXk3JMuAE4YPAArst6VamgJlvsgA0mLj4bNG0OnLaAZCQ1oU9ZNx2jPsVHWpu2US+VpWT2xlouH/iXK+2agE+zrpJ3ZWpmQP2t73F4dadbTQkBeGGeTdec9j8KPmpvfCRJ4
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: openshift-marketplace
    type: kubernetes.io/dockerconfigjson

