apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-cp-datapower-ibm-datapower-instance
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitops-cp-datapower
    server: https://kubernetes.default.svc
  project: 2-services
  source:
    path: payload/2-services/namespace/gitops-cp-datapower/ibm-datapower-instance
    repoURL: >-
      https://github.com/cloud-native-toolkit-test/gitops-cp-datapower-ocp4_cp4i.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
      releaseName: ibm-datapower-instance
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
