apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ibm-entitlement-key
  namespace: gitops-cp-datapower
spec:
  encryptedData:
    .dockerconfigjson: AgBU4b4uL3gBVh3KoG7bJ5X0zl/ofj/GnwD6QmYm3bfGWMnM8fdBGQ1Yuj71DHrvQ7iQKx5Owwiv9FFykI1WYjG20aed8yzc6rQOwQMSb/OKQpg4/M+LVAOw94zyQDnS9oTWrI2RdtPdq875Wh7HrNCp9L7fiOr6KQFrLEISrhYxZaoNuH0nGAPUeb4VgPzPzRCmeP0KFZB/4XVE9Npd5X6qwtj4ZfF3mVF8qdTo/h34gpPrpjBIA7F/GJ1udgJWhHaczkZGQWNXkxYwEJOrB1Kof9FZIL+Q2w/nhAWItEtOC1xbwY6rPDVJXfNJ0dlApr6wWPGzjwrW0/qRRtedUwtdTShwKGGn4WunttnjZJe+GVKlF3FygIgnaTTrB89Z/2vKnoYcduCOK5OI7nzz0+SYmgEZan2NbFoHBVNsMIe72rqBsekXEdgVSs7tRRqwURkJx2XpdBu0PbEG932YfCnayl900vWdGdjEU5NYcFGnTvsR/Z1r9SGqvXrTj4sy3GxMXgzVoLlQ3B1447IN2XpVEU/25Wbw0t1BjlCvWQkNSLuM7pxtN3281gYjm/kycAOUDqGyCfYdjb2G0VLAJjUAOzYNfiuox0FyNtu20307gPaiuiOQszIKik23gQxGH6rROOQrAKv6ZC7QvcCjw8x0BIQCyY0MxiAcNcOASfKtHWxFqwPSMocCaSeT0FJZo8ZnQvRwXLJgVJGe9jzQav11utkIakXdCy/unpT+7KGDNLWoBSddWMGn48TX54fFMYuj9RLmKbpKZY3FSjs4G36BG9yoWwk9Hz447GAeME4yDE5Ec6z+nu/wAu6bE/0m3v12lm9oovzPFystptIeLqbIs6WktHl6cRDUPR2pfUky/oWt1Nxvpeu7ax8n2+mbCmRSqo8fl5FP92iDUnD3QelQ+Wbaz8OiSPaJdolz9ew/6BYzQqrCRTyjkLpFi6UNyaLPGZAokSiWXpMja5dLk+MM8cyBowlXiO7ZujkiAJYLlWJQ36rFF/Y4H5ABilQVmBLAzyN4vI0qFBcM8VKqVTFUC091Sp9Fl/kZPpI23LLgzhhTfa7Wus8Ma7FBwfNn1cipsX7TpYdX2hqp/f6+DhZeFTgYLdEZxVUMYTyZdFKbq2hcalw+BxK23aUMFR9//0MkBpsrSah8caPQiKr/nF/Ju1eO/plTfbYA3/hj9bA0YLM3hYYtqe8w4VoAyjbamOIj7sROayysqgIHypzoZ0kI867toBH+oW5iki5hZeEbT3V0TH+5JfibvgL+9I2mAqT9kJrEUVIFTSkPO782XVhzL6gFUMenF83hFo8+ZSWD6fG6hgeqWUC65CUL3jdDeb2h
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: ibm-entitlement-key
      namespace: gitops-cp-datapower
    type: kubernetes.io/dockerconfigjson

